/**
 * Generated by tsnapi — public API snapshot of `@yunzhen/request`
 */
// #region Re-exports
export * from "axios";
// #endregion

// #region Other
export { authenticateResponseInterceptor }
export { axios }
export { defaultResponseInterceptor }
export { ExtendOptions }
export { HttpResponse }
export { MakeErrorMessageFn }
export { RequestClient }
export { RequestClientConfig }
export { RequestClientOptions }
export { RequestInterceptorConfig }
export { ResponseInterceptorConfig }
// #endregion