/**
 * Generated by tsnapi — public API snapshot of `@yunzhen/request`
 */
// #region Interfaces
export interface ExtendOptions<T = any> {
  paramsSerializer?: 'brackets' | 'comma' | 'indices' | 'repeat' | AxiosRequestConfig<T>['paramsSerializer'];
  responseReturn?: 'body' | 'data' | 'raw';
}
export interface HttpResponse<T = any> {
  code: number;
  data: T;
  message: string;
}
export interface RequestInterceptorConfig {
  fulfilled?: (_: ExtendOptions & InternalAxiosRequestConfig) => (ExtendOptions & InternalAxiosRequestConfig<any>) | Promise<ExtendOptions & InternalAxiosRequestConfig<any>>;
  rejected?: (_: any) => any;
}
export interface ResponseInterceptorConfig<T = any> {
  fulfilled?: (_: RequestResponse<T>) => Promise<RequestResponse> | RequestResponse;
  rejected?: (_: any) => any;
}
// #endregion

// #region Types
export type MakeErrorMessageFn = (_: string, _: any) => void;
export type RequestClientConfig<T = any> = AxiosRequestConfig<T> & ExtendOptions<T>;
export type RequestClientOptions = CreateAxiosDefaults & ExtendOptions;
// #endregion

// #region Classes
export declare class RequestClient {
  isRefreshing: boolean;
  refreshTokenQueue: ((token: string) => void)[];
  private readonly instance;
  constructor(_?: RequestClientOptions);
  addRequestInterceptor({ fulfilled, rejected }?: RequestInterceptorConfig): void;
  addResponseInterceptor<T = any>({ fulfilled, rejected }?: ResponseInterceptorConfig<T>): void;
  get<T = any>(_: string, _?: RequestClientConfig): Promise<T>;
  delete<T = any>(_: string, _?: RequestClientConfig): Promise<T>;
  post<T = any>(_: string, _?: any, _?: RequestClientConfig): Promise<T>;
  put<T = any>(_: string, _?: any, _?: RequestClientConfig): Promise<T>;
  patch<T = any>(_: string, _?: any, _?: RequestClientConfig): Promise<T>;
  request<T>(_: string, _: RequestClientConfig): Promise<T>;
}
// #endregion

// #region Functions
export declare function authenticateResponseInterceptor({ client, doReAuthenticate, doRefreshToken, enableRefreshToken, formatToken }: {
  client: RequestClient;
  doReAuthenticate: () => Promise<void>;
  doRefreshToken: () => Promise<string>;
  enableRefreshToken: boolean;
  formatToken: (_: string) => null | string;
}): ResponseInterceptorConfig;
export declare function defaultResponseInterceptor({ codeField, dataField, successCode }: {
  codeField: string;
  dataField: ((_: any) => any) | string;
  successCode: ((_: any) => boolean) | number | string;
}): ResponseInterceptorConfig;
// #endregion

// #region Re-exports
export * from "axios";
// #endregion

// #region Other
export { axios }
// #endregion